name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-glx

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt

    - name: Test utils
      run: |
        python -m unittest tests/test_utils.py

    - name: Test DataGeneratorNew2
      if: always()
      run: |
        python -m unittest tests/test_datagenerator.py

    - name: Test DataLoaderNew
      if: always()
      run: |
        python -m unittest tests/test_dataloader.py

    - name: Test basic model creation
      if: always()
      run: |
        python -m unittest tests/test_model_creation.py
